targets:
  $default:
    builders:
      jaspr_builder:
        enabled: true
      build_web_compilers:entrypoint:
        generate_for:
          - web/main.dart
        # Use DDC for both development and production builds
        # dart2js has compatibility issues with Jaspr that break event handlers
        # See JASPR_ISSUE_REPORT.md for details
        release_options:
          compiler: dartdevc
        dev_options:
          compiler: dartdevc
